# Taps
tap "homebrew/bundle"
tap "nikitabobko/tap"

# Brews (Packages)
brew "nvm"

# Casks (Applications)
cask "aerospace"
cask "discord"
cask "docker"
cask "google-chrome"
cask "visual-studio-code"
cask "telegram"
cask "notion"
cask "phpstorm"
