# Taps
tap "homebrew/bundle"
tap "nikitabobko/tap"
tap "FelixKratz/formulae"

# Brews (Packages)
brew "nvm"
brew "sketchybar"

# Casks (Applications)
cask "aerospace"
cask "discord"
cask "docker"
cask "google-chrome"
cask "visual-studio-code"
cask "telegram"
cask "notion"
cask "phpstorm"
cask "sequel-ace"
cask "font-hack-nerd-font"
