# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"
export HOMEBREW_BUNDLE_FILE="$HOME/.dotfiles/app/homebrew/Brewfile"

# Source aliases
source ~/.zsh/aliases.zsh

# Source functions
source ~/.zsh/functions.zsh

# Source zinit (plugin manager)
source ~/.zsh/zinit.zsh

# NVM (Node Version Manager)
export NVM_DIR="$HOME/.nvm"
[ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && \. "$(brew --prefix)/opt/nvm/nvm.sh"
[ -s "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm"

# Plugins

# Autosuggestions
zinit light zsh-users/zsh-autosuggestions

# Syntax highlighting
zinit light zdharma-continuum/fast-syntax-highlighting

# Starship theme
zinit ice as"command" from"gh-r" \
          atclone"./starship init zsh > init.zsh; ./starship completions zsh > _starship" \
          atpull"%atclone" src"init.zsh"
zinit light starship/starship

# zinit ice pick"async.zsh" src"pure.zsh"
# zinit light sindresorhus/pure
