" Set line numbers
set nu

" Set tab width to 4 spaces
set tabstop=4

" Set the number of spaces to use for each step of (auto)indent
set shiftwidth=4

" Use spaces instead of tabs when indenting
set expandtab

" Keep indentations consistent
set smartindent
